import Head from "next/head";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Space Tourism</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            {children}
        </>
    );
};

export default Layout;
